name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-dev
        sudo pip3 install --upgrade buildozer
    - name: Build with Buildozer
      run: |
        # دروستکردنی فۆڵدەری مۆڵەتەکان و دانانی پەسەندکردنی ئۆتۆماتیکی
        mkdir -p /home/runner/.android
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk/licenses
        
        # پەسەندکردنی مۆڵەتەکان بە Hash (ئەمە ئەو ڕێگەیە کە گێتهەب قبوڵی دەکات)
        echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo -e "\nd56f5187478651e0694bb1036c730d16c0d8a981" >> /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        
        # دەستپێکردنی بیڵد
        buildozer android debug
      env:
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
