name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-dev unzip openjdk-17-jdk
        sudo pip3 install --upgrade buildozer
    - name: Build with Buildozer
      run: |
        # دروستکردنی فۆڵدەری پێویست
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # بیڵدۆزەر خۆی داوا دەکات مۆڵەتەکان قبوڵ بکەین
        # ئەمجارە هەوڵدەدەین بە دروستی بیڵد بکەین
        buildozer android debug
      env:
        # ئەم گۆڕاوە ڕێگە بە بیڵدۆزەر دەدات مۆڵەتەکان بە ئۆتۆماتیکی قبوڵ بکات
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
